name: Close Issue on PR Merge

on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: read

jobs:
  close_issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Extract Issue Number
        id: extract
        run: |
          # Extract issue number from branch name (assuming format ends with -issue-NUMBER)
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oE 'issue-[0-9]+$' | grep -oE '[0-9]+')
          if [ ! -z "$ISSUE_NUMBER" ]; then
            echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Close Issue
        if: steps.extract.outputs.issue_number != ''
        run: |
          gh issue close ${{ steps.extract.outputs.issue_number }} --repo ${{ github.repository }} --comment "Closing issue as PR [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) has been merged."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
